### ISSUE TITLE
Set up endpoints for roles and user_roles tables

### ISSUE THREAD

**Issue by barancw** [dumparkltd/hr-nmrf-server#140]

**Comment by tmfrnz** [comment]
@barancw after some more deliberation we have decided it will be best to keep the current database schema featuring the already in-place user_role associative table and also to handle all business logic here in the client.

Instead of returning roles with user login, I would suggest to get the roles and user_roles via the API from the respective tables. I am not sure however if the endpoints are properly in place yet? (https://docs.google.com/spreadsheets/d/1U3RHzrneJBZ_VS6RbR6yxlO6EglXMDvR4HqCsfHE2Lk/edit#gid=0)

**Comment by tmfrnz** [comment]
- [x] user_roles
- [ ] roles

**Comment by barancw** [comment]
In roles, only index and show are needed.

In user_roles, managers can promote contributors.  Admins can promote anyone up to admin.
